### PR TITLE
Closes #261 – Parse the strings ourselves instead of relying on RemoteConfig.

### LINKED ISSUE #261: [startup crash] NSInvalidArgumentException format:@"Precision must be less than %d!"
This occurs on a fresh install with the latest upstream/master: f42c9725f05deaec730a7d5f436d3d1d24955b52

The code throws in `GFGeoHash initWithLocation:precision:` where the precision parameter is greater than expected.

### PR DESCRIPTION
**Pull request by jhugman**
The API for RemoteConfig is a little bit funky.

`remoteConfig[key]` will give you back a value object, even if the key doesn't exist.

Worse still, the value object `FIRRemoteConfigValue` will silently fail if the value isn't coercible to the type that we want, or if the key doesn't exist.

So, now: get the `stringValue` out, try and parse it ourselves; if that fails, look for the plist value (which should be correct, but may not be).

If that fails, the fallback further to something a developer typed in to a swift file.

### CODE REVIEW

File: Prox/Prox/AppDelegate.swift [hunk 1]
```diff
@@ -73,7 +73,8 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
 
     private func setupRemoteConfig() {
         let remoteConfig = FIRRemoteConfig.remoteConfig()
-        remoteConfig.configSettings = FIRRemoteConfigSettings(developerModeEnabled: AppConstants.BuildChannel != AppBuildChannel.Release)!
+        let isDeveloperMode = AppConstants.isDebug || AppConstants.MOZ_LOCATION_FAKING
+        remoteConfig.configSettings = FIRRemoteConfigSettings(developerModeEnabled: isDeveloperMode)!
```
Comment (mcomella) [inline Prox/Prox/AppDelegate.swift]: What is developer mode? Are we sure we want it on the "Prox Kona" builds?

File: Prox/Prox/AppDelegate.swift [hunk 2]
```diff
@@ -82,21 +83,21 @@ class AppDelegate: UIResponder, UIApplicationDelegate {
 
         remoteConfig.fetch(withExpirationDuration: remoteConfigCacheExpiration) { status, err in
             if status == FIRRemoteConfigFetchStatus.success {
-                print("RemoteConfig fetched")
+                NSLog("RemoteConfig fetched")
```
Comment (mcomella) [inline Prox/Prox/AppDelegate.swift]: What's the benefit to `NSLog`?

File: Prox/Prox/RemoteConfigKeys.swift [hunk 3]
```diff
@@ -87,16 +87,34 @@ class RemoteConfigProperty<T> {
...
+            }
         }
-        if let rcv = remoteConfig.defaultValue(forKey: key, namespace: nil),
-            let value = convert(rcv) {
-            print("RemoteConfigKeys: Default value for \(key) from embedded plist")
+
+        // TODO: save the last successful value in UserDefaults.standard, then fall back to it here,
+        // instead of falling back to what's in the plist.
+
+        // Check to see if RemoteConfigDefaults.plist has a parseable default
```
Comment (mcomella) [inline Prox/Prox/RemoteConfigKeys.swift]: nit: this is slightly confusing. My understanding is that `remoteConfig[key]` will return a plist value if we call `setDefaultsFromPlistFile` before accessing the remote config.

Thus, its confusing because the comment "check to see if *.plist has a... default" because I'd think we'd already checked the default value in the original `remoteConfig[key]`.

To be clear, I understand what is happening and that this is a fallback: if `remoteConfig[key]` has been overwritten, we need to call `defaultValue` to get the plist value (though it's redundant in the case we've already checked the plist value).

File: Prox/Prox/RemoteConfigKeys.swift [hunk 4]
```diff
@@ -87,16 +87,34 @@ class RemoteConfigProperty<T> {
...
+
+        // rcv is never nil even if there is no key.
+        // rcv.numberValue? never fails either (in light of an invalid number, it defaults to zero).
+        // So, we get the string value, and try parsing it ourselves.
         let rcv = remoteConfig[key]
-        if let value = convert(rcv) {
-            return value
+        if let string = rcv.stringValue {
+            if let value = convert(string) {
+                return value
```
Comment (mcomella) [inline Prox/Prox/RemoteConfigKeys.swift]: Since I assume the empty string is the default value, this will always pass for Strings so we'll never get the type-checked default values of `RemoteConfigPropertyString` – you should remove the default property for Strings and demanded they have plist values.

File: Prox/Prox/RemoteConfigKeys.swift [hunk 5]
```diff
@@ -87,16 +87,34 @@ class RemoteConfigProperty<T> {
...
+            } else if string != "" {
+                // i.e. no default exists, and no value is specified.
+                NSLog("RemoteConfigKeys: Existing value for \(key) is not a valid \(type(of: defaultValue))")
+            }
         }
-        if let rcv = remoteConfig.defaultValue(forKey: key, namespace: nil),
-            let value = convert(rcv) {
-            print("RemoteConfigKeys: Default value for \(key) from embedded plist")
+
+        // TODO: save the last successful value in UserDefaults.standard, then fall back to it here,
```
Comment (mcomella) [inline Prox/Prox/RemoteConfigKeys.swift]: nit: I'm a bit hesitant of writing a cache over Firebase's cache.

File: Prox/Prox/RemoteConfigKeys.swift (hunk 4 above)
Comment (jhugman) [inline Prox/Prox/RemoteConfigKeys.swift]: Added a nil check to `RemoteConfigPropertyString.convert`.

File: Prox/Prox/RemoteConfigKeys.swift (hunk 5 above)
Comment (jhugman) [inline Prox/Prox/RemoteConfigKeys.swift]: yes, me too.

Comment added:

        // This could lead to all sorts of caching related bugs,
        // but would ameliorate the jarring application of a way out of date default.

File: Prox/Prox/RemoteConfigKeys.swift (hunk 3 above)
Comment (jhugman) [inline Prox/Prox/RemoteConfigKeys.swift]: I've added more comments.

TBC: I really don't want to be using the plist. It doesn't help with type info, has terrible failure conditions.

We should *not* use the plist, though there are compelling cases (very long strings) when we could use them. If I started from scratch, I would not support the plist for defaults.

**Comment by jhugman** [comment]
Merged.
