### PR TITLE
Closes #168: hide arrow for travel time loading spinner.

### LINKED ISSUE #168: Travel times loading spinner has forward arrow
A regression from #84, I imagine.

STR:
1) Open app

Expected: Travel times spinner has no arrow
Actual: Has arrow

I don't see it on the simulator but it's pretty apparent on device.

### PR DESCRIPTION
**Pull request by mcomella**

### CODE REVIEW

File: Prox/Prox/PlaceDetails/PlaceDetailsCardViewController.swift [hunk 1]
```diff
@@ -113,13 +113,13 @@ class PlaceDetailsCardViewController: UIViewController {
...
         } else {
-            self.cardView.travelTimeView.loadingSpinner.startAnimating()
+            self.cardView.travelTimeView.isLoading = true
         }
         if let location = location {
             place.travelTimes(fromLocation: location, withCallback: { travelTimes in
-                self.cardView.travelTimeView.loadingSpinner.stopAnimating()
-                guard let travelTimes = travelTimes else { return }
-                self.cardView.updateTravelTimesUI(travelTimes: travelTimes)
+//                self.cardView.travelTimeView.isLoading = false
```
Comment (fluffyemily) [inline Prox/Prox/PlaceDetails/PlaceDetailsCardViewController.swift]: was it your intention to leave these lines commented out? With these lines commented I cannot see how the spinner will every stop spinning?

**Comment by mcomella** [comment]
@fluffyemily Yeah, I pushed to the wrong repo – I believe it should be fixed.
