### PR TITLE
Closes #538: Fix Map and Filter alignment

### LINKED ISSUE #538: Fix Map and Filter alignment
Match specs in mock.

### PR DESCRIPTION
**Pull request by liuche**
Tweaking to match the specs mocks that antlam made for filtering.

### CODE REVIEW

File: Prox/Prox/PlaceDetails/FilterViewController.swift [hunk 1]
```diff
@@ -38,13 +38,21 @@ class FilterViewController: UIViewController {
         fatalError("init(coder:) has not been implemented")
     }
 
+    private func setupShadow(container: UIView) {
+        container.layer.masksToBounds = false
```
Comment (mcomella) [inline Prox/Prox/PlaceDetails/FilterViewController.swift]: For future reference, in my next PR, I defined the shadow qualities in `Style.shadow*`

File: Prox/Prox/PlaceDetails/FilterViewController.swift [hunk 2]
```diff
@@ -62,6 +70,7 @@ class FilterViewController: UIViewController {
             button.isSelected = enabledFilters[i]
             button.tag = i
             button.addTarget(self, action: #selector(didToggleFilter(sender:)), for: .touchUpInside)
+            button.heightAnchor.constraint(equalToConstant: 36)
```
Comment (mcomella) [inline Prox/Prox/PlaceDetails/FilterViewController.swift]: This constraint is unused. In order to activate it, you have to call either:
* `button.heightAnchor.constraint(equalToConstant: 36).isActive = true`
* `NSLayoutConstraint.activate([NSLayoutConstraint])`

File: Prox/Prox/PlaceDetails/FilterViewController.swift [hunk 3]
```diff
@@ -86,7 +95,7 @@ class FilterViewController: UIViewController {
 
         showFilterConstraints += [
             container.topAnchor.constraint(equalTo: view.topAnchor),
-            placeCountLabel.topAnchor.constraint(equalTo: topLayoutGuide.bottomAnchor, constant: spacing),
+            placeCountLabel.topAnchor.constraint(equalTo: topLayoutGuide.topAnchor, constant: 45),
```
Comment (mcomella) [inline Prox/Prox/PlaceDetails/FilterViewController.swift]: I don't  think this is necessary - we have `placeCount` centerY later. Maybe this was necessary because it references topLayoutGuide as the anchor, rather than the container view?

If it is, nit: `topLayoutGuide.topAnchor` -> `view.topAnchor` I think is preferred.

File: Prox/Prox/PlaceDetails/FilterViewController.swift [hunk 4]
```diff
@@ -103,20 +112,21 @@ class FilterViewController: UIViewController {
             container.leadingAnchor.constraint(equalTo: view.leadingAnchor),
 
             placeCountLabel.centerXAnchor.constraint(equalTo: container.centerXAnchor),
+            placeCountLabel.centerYAnchor.constraint(equalTo: closeButton.centerYAnchor),
 
-            closeButton.centerYAnchor.constraint(equalTo: placeCountLabel.centerYAnchor),
-            closeButton.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -spacing),
+            closeButton.topAnchor.constraint(equalTo: view.topAnchor, constant: 45),
```
Comment (mcomella) [inline Prox/Prox/PlaceDetails/FilterViewController.swift]: Should this be `container.topAnchor`? I'm concerned this will continue to draw (underneath the photo carousel?) if it's constrained to the outer outer view.

File: Prox/Prox/PlaceDetails/PlaceDetailViewController.swift [hunk 5]
```diff
@@ -251,8 +251,8 @@ class PlaceDetailViewController: UIViewController {
         }
 
         view.addSubview(mapButton)
-        constraints += [mapButton.topAnchor.constraint(equalTo: view.topAnchor, constant: 36),
-                        mapButton.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 16),
+        constraints += [mapButton.topAnchor.constraint(equalTo: view.topAnchor, constant: 20),
```
Comment (mcomella) [inline Prox/Prox/PlaceDetails/PlaceDetailViewController.swift]: nit: constant?
