### PR TITLE
Closes #217: Add placeholder images when missing from image carousel

### LINKED ISSUE #217: if image is not present do not display carousel
Feels rather broken to swipe through a set of blank images
screen shot 2016-11-18 at 2 01 14 pm

### PR DESCRIPTION
**Pull request by mcomella**
#217

### CODE REVIEW

File: Prox/Prox/MapPlacesTransition.swift [hunk 1]
```diff
@@ -161,7 +165,7 @@ class MapPlacesTransition: NSObject, UIViewControllerAnimatedTransitioning {
             fakeImageView.contentMode = UIViewContentMode.scaleAspectFill
             fakeImageView.clipsToBounds = true
             fakeImageView.backgroundColor = .red
```
Comment (sleroux) [inline Prox/Prox/MapPlacesTransition.swift]: This might be the red that you're seeing. I must have left this in from debugging :(
